spring:
#  datasource:
#    url: jdbc:mysql://minidb.c74fq5jjb22v.ap-northeast-2.rds.amazonaws.com:3306/minidb?serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root1234
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace